import Head from 'next/head';
import Image from 'next/image';
import useSWR from 'swr';
import { Grid, CircularProgress } from '@mui/material';
import styles from '../styles/Home.module.css';
import Navigation from '../components/Navigation';

const fetcher = (url) => fetch(url).then((res) => res.json());

const Store = () => {
  const { data, error } = useSWR('http://localhost:9000/stores', fetcher);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <Grid
          container
          spacing={{ xs: 2, md: 3 }}
          columns={{ xs: 4, sm: 4, md: 4 }}
          justifyContent='center'
          alignItems='center'
        >
          {data ? (
            data.map((restaurant) => {
              return (
                <Grid
                  item
                  xs={1}
                  key={restaurant.index}
                  className={styles.grid}
                >
                  <article className={styles.card}>
                    <Image
                      src={restaurant.thumb}
                      alt=''
                      width='200'
                      height='200'
                    />
                  </article>
                </Grid>
              );
            })
          ) : (
            <CircularProgress />
          )}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://www.n8patterson.com/'
          target='_blank'
          rel='noopener noreferrer'
        >
          @ 2021 Nathan Patterson
        </a>
      </footer>
    </div>
  );
};

export default Store;
